import OrderContextProvider from './context/order'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body className={`h-screen w-screen ${inter.className}`}>
        <OrderContextProvider>
          {children}
        </OrderContextProvider>
      </body>
    </html>
  )
}
